spring:
  application:
    name: api-gateway

server:
  port: 8080

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  routes:
    inventory-service:
      path: /inventory/**
      url: http://inventory-service:8081
    review-service:
        path: /reviews/**
        url: http://review-service:8082
    order-service:
      path: /order/**
      url: http://order-service:8099
    shopping-cart:
      path: /shopping-cart/**
      url: http://shopping-cart:8084
    recommendation-service:
      path: /recommendation/**
      url: http://recommendation-service:8077
